services:
  # ================================================================
  # 💻 ENTORNO DE DESARROLLO (Active Profile: local)
  # ================================================================
  postgres:
    image: postgres:17.3
    container_name: postgres
    restart: always
    profiles: ["local"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 5

  mosquitto-local:
    image: eclipse-mosquitto
    container_name: mosquitto-local
    restart: always
    profiles: ["local"]
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./infrastructure/mosquitto-local/config:/mosquitto/config
      - ./infrastructure/mosquitto-local/data:/mosquitto/data
      - ./infrastructure/mosquitto-local/log:/mosquitto/log

  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    restart: always
    profiles: ["local"]
    ports:
      - "8181:8181" 
    volumes:
      - ./infrastructure/influxdb/data:/var/lib/influxdb3/data
    environment:
      INFLUXD_ADMIN_TOKEN: ${INFLUX_TOKEN}
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --http-bind=0.0.0.0:8181

  # ----------------------------------------------------------------
  # SERVICIOS LOCALES 
  # ----------------------------------------------------------------
  ingest-local:
    container_name: ingest-local
    profiles: ["local"]
    build:
      context: .
      dockerfile: services/ingest/Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto-local:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL_LOCAL}

      DB_HOST: postgres
      DB_USER: ${DB_USER}

      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_URL: ${INFLUX_URL_LOCAL}

      MQTT_BROKER_URL: ${MQTT_BROKER_URL_LOCAL}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID_INGEST}-LOCAL
      MQTT_PASSWORD: ${MQTT_PASS_BACKEND}
      MQTT_USERNAME: ${MQTT_USER_BACKEND}

      NODE_ENV: development
      NODE_OPTIONS: "--dns-result-order=ipv4first"

  scheduler-local:
    container_name: scheduler-local
    profiles: ["local"]
    build:
      context: .
      dockerfile: services/scheduler/Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto-local:
        condition: service_started
      influxdb:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL_LOCAL}

      DB_HOST: postgres
      DB_USER: ${DB_USER}

      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_URL: ${INFLUX_URL_LOCAL}

      MQTT_BROKER_URL: ${MQTT_BROKER_URL_LOCAL}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID_SCHEDULER}-LOCAL
      MQTT_PASSWORD: ${MQTT_PASS_BACKEND}
      MQTT_USERNAME: ${MQTT_USER_BACKEND}

      NODE_ENV: development
      NODE_OPTIONS: "--dns-result-order=ipv4first"


  # ================================================================
  # ☁️ INFRAESTRUCTURA DE PRODUCCIÓN (Active Profile: vps)
  # ================================================================
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    profiles: ["vps"]
    ports:
      - "8883:8883"  # MQTTS (Hardware ESP32)
      - "8884:8884"  # WSS (WebSockets Vercel - Compatible HiveMQ)
    volumes:
      - ./infrastructure/mosquitto/config:/mosquitto/config
      - ./infrastructure/mosquitto/data:/mosquitto/data
      - ./infrastructure/mosquitto/log:/mosquitto/log
      - ./infrastructure/certs:/mosquitto/certs:ro


  # ================================================================
  # 🚀 SERVICIOS DE PRODUCCIÓN (Active Profile: cloud)
  # ================================================================
  ingest:
    container_name: ingest
    profiles: ["cloud"]
    build:
      context: .
      dockerfile: services/ingest/Dockerfile
      extra_hosts:
        - "registry.npmjs.org:104.16.27.35"
    restart: always
    environment:
      DATABASE_URL_UNPOOLED: ${DATABASE_URL_CLOUD_UNPOOLED}
      DATABASE_URL: ${DATABASE_URL_CLOUD}

      DB_HOST: ${DB_HOST_CLOUD}
      DB_USER: ${DB_USER_CLOUD}

      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_URL: ${INFLUX_URL_CLOUD}

      MQTT_BROKER_URL: ${MQTT_BROKER_URL_CLOUD} 
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID_INGEST}
      MQTT_PASSWORD: ${MQTT_PASS_BACKEND}
      MQTT_USERNAME: ${MQTT_USER_BACKEND}

      NODE_ENV: development
      NODE_OPTIONS: "--dns-result-order=ipv4first"


  scheduler:
    container_name: scheduler
    profiles: ["cloud"]
    build:
      context: .
      dockerfile: services/scheduler/Dockerfile
      extra_hosts:
        - "registry.npmjs.org:104.16.27.35"
    restart: always
    # Sin dependencia de infraestructura. Puede conectar a HiveMQ o VPS.
    environment:
      DATABASE_URL_UNPOOLED: ${DATABASE_URL_CLOUD_UNPOOLED}
      DATABASE_URL: ${DATABASE_URL_CLOUD}

      DB_HOST: ${DB_HOST_CLOUD}
      DB_USER: ${DB_USER_CLOUD}

      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_URL: ${INFLUX_URL_CLOUD}

      MQTT_BROKER_URL: ${MQTT_BROKER_URL_CLOUD}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID_SCHEDULER}
      MQTT_PASSWORD: ${MQTT_PASS_BACKEND}
      MQTT_USERNAME: ${MQTT_USER_BACKEND}

      NODE_ENV: development
      NODE_OPTIONS: "--dns-result-order=ipv4first"


networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350