-- CreateTable
CREATE TABLE IF NOT EXISTS "SchedulerState" (
    "id" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "lastEvaluation" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SchedulerState_pkey" PRIMARY KEY ("id")
);

-- AlterTable (DailyEnvironmentStat)
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "avgHumDay" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "avgHumNight" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "maxHumDay" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "maxHumDayTime" TEXT;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "maxHumNight" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "maxHumNightTime" TEXT;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "maxTempDay" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "maxTempDayTime" TEXT;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "maxTempNight" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "maxTempNightTime" TEXT;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "minHumDay" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "minHumDayTime" TEXT;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "minHumNight" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "minHumNightTime" TEXT;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "minTempDay" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "minTempDayTime" TEXT;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "minTempNight" DOUBLE PRECISION;
ALTER TABLE "DailyEnvironmentStat" ADD COLUMN IF NOT EXISTS "minTempNightTime" TEXT;

-- AlterTable (RainEvent)
ALTER TABLE "RainEvent" ADD COLUMN IF NOT EXISTS "startTemp" DOUBLE PRECISION;
ALTER TABLE "RainEvent" ADD COLUMN IF NOT EXISTS "startHum" DOUBLE PRECISION;
ALTER TABLE "RainEvent" ADD COLUMN IF NOT EXISTS "startLux" DOUBLE PRECISION;
ALTER TABLE "RainEvent" ADD COLUMN IF NOT EXISTS "endTemp" DOUBLE PRECISION;
ALTER TABLE "RainEvent" ADD COLUMN IF NOT EXISTS "endHum" DOUBLE PRECISION;
ALTER TABLE "RainEvent" ADD COLUMN IF NOT EXISTS "endLux" DOUBLE PRECISION;
