# Configuración General y Persistencia
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Seguridad y Autenticación
allow_anonymous false
password_file /mosquitto/config/passwd

# Frente 1: Red Interna Docker (Backend Ingest/Scheduler)
listener 1883
protocol mqtt

# Frente 2: Hardware ESP32 (MQTTS - Seguro)
listener 8883
protocol mqtt
certfile /mosquitto/certs/live/mqtt.sisparrow.com/fullchain.pem
keyfile /mosquitto/certs/live/mqtt.sisparrow.com/privkey.pem

# Frente 3: Frontend Vercel (WSS - WebSockets Seguros)
listener 8884
protocol websockets
certfile /mosquitto/certs/live/mqtt.sisparrow.com/fullchain.pem
keyfile /mosquitto/certs/live/mqtt.sisparrow.com/privkey.pem