-- AlterEnum
ALTER TYPE "DosageUnit" ADD VALUE IF NOT EXISTS 'CDA_L';
ALTER TYPE "DosageUnit" ADD VALUE IF NOT EXISTS 'CDITA_L';
ALTER TYPE "DosageUnit" ADD VALUE IF NOT EXISTS 'CDITA_PLANTA';
ALTER TYPE "DosageUnit" ADD VALUE IF NOT EXISTS 'G_PLANTA';
ALTER TYPE "DosageUnit" ADD VALUE IF NOT EXISTS 'ML_PLANTA';
ALTER TYPE "DosageUnit" ADD VALUE IF NOT EXISTS 'PORCENTAJE';
ALTER TYPE "DosageUnit" ADD VALUE IF NOT EXISTS 'GOTAS_L';
ALTER TYPE "DosageUnit" ADD VALUE IF NOT EXISTS 'CC_L';
