-- AlterEnum
ALTER TYPE "PotSize" ADD VALUE IF NOT EXISTS 'NRO_3';
ALTER TYPE "PotSize" ADD VALUE IF NOT EXISTS 'NRO_8';
ALTER TYPE "PotSize" ADD VALUE IF NOT EXISTS 'NRO_12';
ALTER TYPE "PotSize" ADD VALUE IF NOT EXISTS 'NRO_15';
ALTER TYPE "PotSize" ADD VALUE IF NOT EXISTS 'CT1';
ALTER TYPE "PotSize" ADD VALUE IF NOT EXISTS 'CT2';
ALTER TYPE "PotSize" ADD VALUE IF NOT EXISTS 'CT3';
ALTER TYPE "PotSize" ADD VALUE IF NOT EXISTS 'CT4';
